name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Find all APKs
      run: |
        mkdir -p apk-outputs
        find . -type f -name "*.apk" -exec cp {} apk-outputs/ \;
      shell: bash

    - name: Upload APK(s)
      uses: actions/upload-artifact@v4
      with:
        name: all-apks
        path: apk-outputs/*.apk
